# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HFiol0PYABpEKhY8V4ULhFKVtzlS3Z48
"""

from flask import Flask, render_template
from matrix_multiplier import matrix_multiplication_with_diagonal_matrix

app = Flask(__name__)

@app.route("/")
def index():
    A, D, result = matrix_multiplication_with_diagonal_matrix()
    return render_template("index.html", A=A, D=D, result=result)

if __name__ == "__main__":
    app.run(debug=True)