# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rEpM5si1t3EzOKcI-Z4MaLCdABo1OYFC
"""

# matrix_generator.py

import numpy as np

def generate_matrix():
    A = np.array([[1, 0, 1, 0, 0, 1],
                  [0, 1, 0, 1, 0, 1],
                  [1, 0, 1, 0, 1, 0],
                  [0, 1, 0, 1, 0, 1],
                  [0, 0, 1, 0, 1, 0],
                  [1, 1, 0, 1, 0, 1]])

    return A

def generate_diagonal_matrix():
    D = np.diag([2, 3, 1])
    return D

