# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rEpM5si1t3EzOKcI-Z4MaLCdABo1OYFC
"""

# matrix_multiplier.py

import numpy as np
from matrix_generator import generate_matrix, generate_diagonal_matrix

def matrix_multiplication_with_diagonal_matrix():
    A = generate_matrix()
    D = generate_diagonal_matrix()
    result = np.dot(A, D)
    return result

