# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rEpM5si1t3EzOKcI-Z4MaLCdABo1OYFC
"""

# main.py

from matrix_multiplier import matrix_multiplication_with_diagonal_matrix

def main():
    print("행렬과 대각행렬의 곱 결과:")
    result = matrix_multiplication_with_diagonal_matrix()
    print(result)

if __name__ == "__main__":
    main()

